### ISSUE TITLE
Getting error after running ./gradlew :kafka-spark:run -Pargs=/pankh-master/kafka-spark/conf/analyzer.conf

### ISSUE THREAD

**Issue by rmarjun** [SinghAsDev/pankh#1]
Getting error after running ./gradlew :kafka-spark:run -Pargs=/pankh-master/kafka-spark/conf/analyzer.conf

Exception in thread "main" org.apache.spark.SparkException: java.net.ConnectException: Connection refused
    at org.apache.spark.streaming.kafka.KafkaUtils$$anonfun$createDirectStream$2.apply(KafkaUtils.scala:413)
    at org.apache.spark.streaming.kafka.KafkaUtils$$anonfun$createDirectStream$2.apply(KafkaUtils.scala:413)
    at scala.util.Either.fold(Either.scala:97)
    at org.apache.spark.streaming.kafka.KafkaUtils$.createDirectStream(KafkaUtils.scala:412)
    at org.apache.spark.streaming.kafka.KafkaUtils$.createDirectStream(KafkaUtils.scala:528)
    at org.apache.spark.streaming.kafka.KafkaUtils.createDirectStream(KafkaUtils.scala)
    at com.singhasdev.pankh.analysis.SentimentAnalysis.main(SentimentAnalysis.java:79)

**Comment by rmarjun** [comment]
Whether to run kafka producer/consumer before executing following scripts?
./gradlew :twitter-kafka:run -Pargs=/pankh-master/twitter-kafka/conf/producer.conf
./gradlew :kafka-spark:run -Pargs=/pankh-master/kafka-spark/conf/analyzer.conf

Does we need to start spark-master also or the script do itself?

**Comment by raveenpereira** [comment]
Same error
